name: Автоматические тесты

on: [push]

permissions:
  checks: write
  actions: read
  contents: read
  issues: write

jobs:
  test:
    permissions: write-all
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: ".github/tests/pnpm-lock.yaml"

      - name: Install dependencies
        run: "cd .github/tests && pnpm install"

      - name: Run tests
        id: run-tests
        run: "cd .github/tests && pnpm run test"

      - name: Comment PR
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            console.log(context)
            await github.rest.issues.createComment({
              issue_number: 1,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ("${{steps.run-tests.outcome}}" === "success" ? "✅ Тесты проходят ✅" : "‼️ Тесты не проходят ‼️\nЕсли это ошибка линтера вы можете посмотреть ошибки во вкладке \"Files changed\" наверху страницы.") +
              `\n[Результат запуска тестов](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})`
            })
